version: "2"
formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt

linters:
  enable:
    - errcheck
    - errname
    - errorlint
    - govet
    - nilerr
    - nilnesserr
    - rowserrcheck
    - unconvert
    - unparam
    - unused
    - wrapcheck

  settings:
    staticcheck:
      checks:
        - all
        - -QF1008
        - -ST1000

    errcheck:
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
      check-blank: true

    wrapcheck:
      extra-ignore-sigs:
        - .Close()
        - .Ping(
        - .Rollback()
        - .Value()
        - db.OpenDBConnectionPool
        - db.RunInTransaction
        - json.Marshal
        - json.Unmarshal

  exclusions:
    paths:
      # mocks are ignored
      - ".*.mock.*\\.go$"

    rules:
      - path: _test\.go
        linters: [wrapcheck]

      - path: (_test\.go|dbtest\.go|fixtures\.go|test_utils\.go|.*/testutils/.*)$
        linters: [errcheck]
        text: '\.Close()|\.Rollback()|\.Execute()'

      # Exclude some `staticcheck` messages.
      - linters: [staticcheck]
        text: '(SqlDB should be SQLDB)' # allow SqlDB because some dependencies (sql & sqlx) use SqlDB.

      - linters: [staticcheck]
        path: _test\.go
        text: '(QF1003)'

    # Mode of the generated files analysis.
    #
    # - `strict`: Only fules containing `^// Code generated .* DO NOT EDIT\.$` are excluded.
    # - `lax`: Sources containing lines like `autogenerated file`, `code generated`, `do not edit`, etc. are excluded.
    # - `disable`: disable the generated files exclusion.
    #
    # Default: strict
    generated: lax
