version: "2"
formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt

linters:
  enable:
    - govet
    - rowserrcheck
    - nilerr
    - nilnesserr
    # - errname
    # - errorlint
    # - errcheck
    # - wrapcheck
    - unused
    - unconvert
    - unparam

  default: none

  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -QF1008

    errcheck:
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
      check-blank: true

  exclusions:
    paths:
      # mocks are ignored
      - ".*.mock.*\\.go$"

    rules:
      - path: _test\.go
        linters: [wrapcheck]

      - path: (_test\.go|dbtest\.go)$
        linters: [errcheck]
        text: '\.Close()|\.Rollback()'

      # Exclude some `staticcheck` messages.
      - linters: [staticcheck]
        text: '(QF1008|SqlDB should be SQLDB)'

    # Mode of the generated files analysis.
    #
    # - `strict`: Only fules containing `^// Code generated .* DO NOT EDIT\.$` are excluded.
    # - `lax`: Sources containing lines like `autogenerated file`, `code generated`, `do not edit`, etc. are excluded.
    # - `disable`: disable the generated files exclusion.
    #
    # Default: strict
    generated: lax
