// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CodeGeneratorMock is an autogenerated mock type for the CodeGenerator type
type CodeGeneratorMock struct {
	mock.Mock
}

// Generate provides a mock function with given fields: length
func (_m *CodeGeneratorMock) Generate(length int) string {
	ret := _m.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(length)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewCodeGeneratorMock creates a new instance of CodeGeneratorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodeGeneratorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodeGeneratorMock {
	mock := &CodeGeneratorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
