FROM node:18-alpine as builder

RUN apk add --no-cache git

RUN git clone https://github.com/stellar/stellar-demo-wallet.git /app
WORKDIR /app

RUN yarn workspace demo-wallet-client install
RUN yarn build:shared
RUN yarn build:client

# Use Nginx to serve the demo-wallet client
FROM nginx:1.25-alpine
COPY --from=builder /app/packages/demo-wallet-client/build/ /usr/share/nginx/html/
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf