version: '3'
services:
  db-conduktor:
    image: postgres:14
    hostname: postgresql
    volumes:
      - db-conduktor-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "conduktor-platform"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "change_me"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  conduktor-platform:
    image: conduktor/conduktor-platform:1.19.2
    ports:
      - "9090:8080"
    volumes:
      - conduktor-platform-data:/var/conduktor
    environment:
      CDK_DATABASE_URL: "postgresql://conduktor:change_me@db-conduktor:5432/conduktor-platform"
      CDK_MONITORING_CORTEX-URL: http://conduktor-monitoring:9009/
      CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-monitoring:9010/
      CDK_MONITORING_CALLBACK-URL: http://conduktor-platform:9090/monitoring/api/
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:9090
    healthcheck:
      test: curl -f http://localhost:9090/platform/api/modules/health/live || exit 1
      interval: 10s
      start_period: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - db-conduktor

  conduktor-monitoring:
    image: conduktor/conduktor-platform-cortex:1.19.2
    environment:
      CDK_CONSOLE-URL: "http://conduktor-platform:9090"

volumes:
  db-conduktor-data:
    driver: local
  conduktor-platform-data:
    driver: local