// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/stellar/stellar-disbursement-platform-backend/db"
	mock "github.com/stretchr/testify/mock"

	store "github.com/stellar/stellar-disbursement-platform-backend/internal/transactionsubmission/store"
)

// MockTransactionStore is an autogenerated mock type for the TransactionStore type
type MockTransactionStore struct {
	mock.Mock
}

// BulkInsert provides a mock function with given fields: ctx, sqlExec, transactions
func (_m *MockTransactionStore) BulkInsert(ctx context.Context, sqlExec db.SQLExecuter, transactions []store.Transaction) ([]store.Transaction, error) {
	ret := _m.Called(ctx, sqlExec, transactions)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsert")
	}

	var r0 []store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLExecuter, []store.Transaction) ([]store.Transaction, error)); ok {
		return rf(ctx, sqlExec, transactions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLExecuter, []store.Transaction) []store.Transaction); ok {
		r0 = rf(ctx, sqlExec, transactions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.SQLExecuter, []store.Transaction) error); ok {
		r1 = rf(ctx, sqlExec, transactions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, txID
func (_m *MockTransactionStore) Get(ctx context.Context, txID string) (*store.Transaction, error) {
	ret := _m.Called(ctx, txID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*store.Transaction, error)); ok {
		return rf(ctx, txID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *store.Transaction); ok {
		r0 = rf(ctx, txID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, txID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllByExternalIDs provides a mock function with given fields: ctx, externalIDs
func (_m *MockTransactionStore) GetAllByExternalIDs(ctx context.Context, externalIDs []string) ([]*store.Transaction, error) {
	ret := _m.Called(ctx, externalIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByExternalIDs")
	}

	var r0 []*store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*store.Transaction, error)); ok {
		return rf(ctx, externalIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*store.Transaction); ok {
		r0 = rf(ctx, externalIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, externalIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionBatchForUpdate provides a mock function with given fields: ctx, dbTx, batchSize, tenantID, transactionType
func (_m *MockTransactionStore) GetTransactionBatchForUpdate(ctx context.Context, dbTx db.DBTransaction, batchSize int, tenantID string, transactionType store.TransactionType) ([]*store.Transaction, error) {
	ret := _m.Called(ctx, dbTx, batchSize, tenantID, transactionType)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionBatchForUpdate")
	}

	var r0 []*store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.DBTransaction, int, string, store.TransactionType) ([]*store.Transaction, error)); ok {
		return rf(ctx, dbTx, batchSize, tenantID, transactionType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.DBTransaction, int, string, store.TransactionType) []*store.Transaction); ok {
		r0 = rf(ctx, dbTx, batchSize, tenantID, transactionType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.DBTransaction, int, string, store.TransactionType) error); ok {
		r1 = rf(ctx, dbTx, batchSize, tenantID, transactionType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionPendingUpdateByID provides a mock function with given fields: ctx, sqlExec, txID, expectedTransactionType
func (_m *MockTransactionStore) GetTransactionPendingUpdateByID(ctx context.Context, sqlExec db.SQLExecuter, txID string, expectedTransactionType store.TransactionType) (*store.Transaction, error) {
	ret := _m.Called(ctx, sqlExec, txID, expectedTransactionType)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionPendingUpdateByID")
	}

	var r0 *store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLExecuter, string, store.TransactionType) (*store.Transaction, error)); ok {
		return rf(ctx, sqlExec, txID, expectedTransactionType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLExecuter, string, store.TransactionType) *store.Transaction); ok {
		r0 = rf(ctx, sqlExec, txID, expectedTransactionType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.SQLExecuter, string, store.TransactionType) error); ok {
		r1 = rf(ctx, sqlExec, txID, expectedTransactionType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, tx
func (_m *MockTransactionStore) Insert(ctx context.Context, tx store.Transaction) (*store.Transaction, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.Transaction) (*store.Transaction, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.Transaction) *store.Transaction); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.Transaction) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lock provides a mock function with given fields: ctx, sqlExec, transactionID, currentLedger, nextLedgerLock
func (_m *MockTransactionStore) Lock(ctx context.Context, sqlExec db.SQLExecuter, transactionID string, currentLedger int32, nextLedgerLock int32) (*store.Transaction, error) {
	ret := _m.Called(ctx, sqlExec, transactionID, currentLedger, nextLedgerLock)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 *store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLExecuter, string, int32, int32) (*store.Transaction, error)); ok {
		return rf(ctx, sqlExec, transactionID, currentLedger, nextLedgerLock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLExecuter, string, int32, int32) *store.Transaction); ok {
		r0 = rf(ctx, sqlExec, transactionID, currentLedger, nextLedgerLock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.SQLExecuter, string, int32, int32) error); ok {
		r1 = rf(ctx, sqlExec, transactionID, currentLedger, nextLedgerLock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrepareTransactionForReprocessing provides a mock function with given fields: ctx, sqlExec, transactionID
func (_m *MockTransactionStore) PrepareTransactionForReprocessing(ctx context.Context, sqlExec db.SQLExecuter, transactionID string) (*store.Transaction, error) {
	ret := _m.Called(ctx, sqlExec, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for PrepareTransactionForReprocessing")
	}

	var r0 *store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLExecuter, string) (*store.Transaction, error)); ok {
		return rf(ctx, sqlExec, transactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLExecuter, string) *store.Transaction); ok {
		r0 = rf(ctx, sqlExec, transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.SQLExecuter, string) error); ok {
		r1 = rf(ctx, sqlExec, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unlock provides a mock function with given fields: ctx, sqlExec, publicKey
func (_m *MockTransactionStore) Unlock(ctx context.Context, sqlExec db.SQLExecuter, publicKey string) (*store.Transaction, error) {
	ret := _m.Called(ctx, sqlExec, publicKey)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 *store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLExecuter, string) (*store.Transaction, error)); ok {
		return rf(ctx, sqlExec, publicKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLExecuter, string) *store.Transaction); ok {
		r0 = rf(ctx, sqlExec, publicKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.SQLExecuter, string) error); ok {
		r1 = rf(ctx, sqlExec, publicKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatusToError provides a mock function with given fields: ctx, tx, message
func (_m *MockTransactionStore) UpdateStatusToError(ctx context.Context, tx store.Transaction, message string) (*store.Transaction, error) {
	ret := _m.Called(ctx, tx, message)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusToError")
	}

	var r0 *store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.Transaction, string) (*store.Transaction, error)); ok {
		return rf(ctx, tx, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.Transaction, string) *store.Transaction); ok {
		r0 = rf(ctx, tx, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.Transaction, string) error); ok {
		r1 = rf(ctx, tx, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatusToSuccess provides a mock function with given fields: ctx, tx
func (_m *MockTransactionStore) UpdateStatusToSuccess(ctx context.Context, tx store.Transaction) (*store.Transaction, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusToSuccess")
	}

	var r0 *store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.Transaction) (*store.Transaction, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.Transaction) *store.Transaction); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.Transaction) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStellarTransactionHashXDRSentAndDistributionAccount provides a mock function with given fields: ctx, txID, txHash, txXDRSent, distributionAccount
func (_m *MockTransactionStore) UpdateStellarTransactionHashXDRSentAndDistributionAccount(ctx context.Context, txID string, txHash string, txXDRSent string, distributionAccount string) (*store.Transaction, error) {
	ret := _m.Called(ctx, txID, txHash, txXDRSent, distributionAccount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStellarTransactionHashXDRSentAndDistributionAccount")
	}

	var r0 *store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*store.Transaction, error)); ok {
		return rf(ctx, txID, txHash, txXDRSent, distributionAccount, distributionAccount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *store.Transaction); ok {
		r0 = rf(ctx, txID, txHash, txXDRSent, distributionAccount, distributionAccount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, txID, txHash, txXDRSent, distributionAccount, distributionAccount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStellarTransactionXDRReceived provides a mock function with given fields: ctx, txID, xdrReceived
func (_m *MockTransactionStore) UpdateStellarTransactionXDRReceived(ctx context.Context, txID string, xdrReceived string) (*store.Transaction, error) {
	ret := _m.Called(ctx, txID, xdrReceived)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStellarTransactionXDRReceived")
	}

	var r0 *store.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*store.Transaction, error)); ok {
		return rf(ctx, txID, xdrReceived)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *store.Transaction); ok {
		r0 = rf(ctx, txID, xdrReceived)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, txID, xdrReceived)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSyncedTransactions provides a mock function with given fields: ctx, sqlExec, txIDs
func (_m *MockTransactionStore) UpdateSyncedTransactions(ctx context.Context, sqlExec db.SQLExecuter, txIDs []string) error {
	ret := _m.Called(ctx, sqlExec, txIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSyncedTransactions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.SQLExecuter, []string) error); ok {
		r0 = rf(ctx, sqlExec, txIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockTransactionStore creates a new instance of MockTransactionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionStore {
	mock := &MockTransactionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
