// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	context "context"

	keypair "github.com/stellar/go/keypair"

	mock "github.com/stretchr/testify/mock"

	txnbuild "github.com/stellar/go/txnbuild"
)

// MockSignatureService is an autogenerated mock type for the SignatureService type
type MockSignatureService struct {
	mock.Mock
}

// BatchInsert provides a mock function with given fields: ctx, kps, shouldEncryptSeed, currLedgerNumber
func (_m *MockSignatureService) BatchInsert(ctx context.Context, kps []*keypair.Full, shouldEncryptSeed bool, currLedgerNumber int) error {
	ret := _m.Called(ctx, kps, shouldEncryptSeed, currLedgerNumber)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*keypair.Full, bool, int) error); ok {
		r0 = rf(ctx, kps, shouldEncryptSeed, currLedgerNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, publicKey, currLedgerNumber
func (_m *MockSignatureService) Delete(ctx context.Context, publicKey string, currLedgerNumber int) error {
	ret := _m.Called(ctx, publicKey, currLedgerNumber)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, publicKey, currLedgerNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DistributionAccount provides a mock function with given fields:
func (_m *MockSignatureService) DistributionAccount() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NetworkPassphrase provides a mock function with given fields:
func (_m *MockSignatureService) NetworkPassphrase() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SignFeeBumpStellarTransaction provides a mock function with given fields: ctx, feeBumpStellarTx, stellarAccounts
func (_m *MockSignatureService) SignFeeBumpStellarTransaction(ctx context.Context, feeBumpStellarTx *txnbuild.FeeBumpTransaction, stellarAccounts ...string) (*txnbuild.FeeBumpTransaction, error) {
	_va := make([]interface{}, len(stellarAccounts))
	for _i := range stellarAccounts {
		_va[_i] = stellarAccounts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, feeBumpStellarTx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *txnbuild.FeeBumpTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *txnbuild.FeeBumpTransaction, ...string) (*txnbuild.FeeBumpTransaction, error)); ok {
		return rf(ctx, feeBumpStellarTx, stellarAccounts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *txnbuild.FeeBumpTransaction, ...string) *txnbuild.FeeBumpTransaction); ok {
		r0 = rf(ctx, feeBumpStellarTx, stellarAccounts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*txnbuild.FeeBumpTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *txnbuild.FeeBumpTransaction, ...string) error); ok {
		r1 = rf(ctx, feeBumpStellarTx, stellarAccounts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignStellarTransaction provides a mock function with given fields: ctx, stellarTx, stellarAccounts
func (_m *MockSignatureService) SignStellarTransaction(ctx context.Context, stellarTx *txnbuild.Transaction, stellarAccounts ...string) (*txnbuild.Transaction, error) {
	_va := make([]interface{}, len(stellarAccounts))
	for _i := range stellarAccounts {
		_va[_i] = stellarAccounts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, stellarTx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *txnbuild.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *txnbuild.Transaction, ...string) (*txnbuild.Transaction, error)); ok {
		return rf(ctx, stellarTx, stellarAccounts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *txnbuild.Transaction, ...string) *txnbuild.Transaction); ok {
		r0 = rf(ctx, stellarTx, stellarAccounts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*txnbuild.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *txnbuild.Transaction, ...string) error); ok {
		r1 = rf(ctx, stellarTx, stellarAccounts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockSignatureService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSignatureService creates a new instance of MockSignatureService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSignatureService(t mockConstructorTestingTNewMockSignatureService) *MockSignatureService {
	mock := &MockSignatureService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
