// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	message "github.com/stellar/stellar-disbursement-platform-backend/internal/message"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageDispatcher is an autogenerated mock type for the MessageDispatcherInterface type
type MockMessageDispatcher struct {
	mock.Mock
}

// GetClient provides a mock function with given fields: channel
func (_m *MockMessageDispatcher) GetClient(channel message.MessageChannel) (message.MessengerClient, error) {
	ret := _m.Called(channel)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 message.MessengerClient
	var r1 error
	if rf, ok := ret.Get(0).(func(message.MessageChannel) (message.MessengerClient, error)); ok {
		return rf(channel)
	}
	if rf, ok := ret.Get(0).(func(message.MessageChannel) message.MessengerClient); ok {
		r0 = rf(channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(message.MessengerClient)
		}
	}

	if rf, ok := ret.Get(1).(func(message.MessageChannel) error); ok {
		r1 = rf(channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterClient provides a mock function with given fields: ctx, channel, client
func (_m *MockMessageDispatcher) RegisterClient(ctx context.Context, channel message.MessageChannel, client message.MessengerClient) {
	_m.Called(ctx, channel, client)
}

// SendMessage provides a mock function with given fields: _a0, channel
func (_m *MockMessageDispatcher) SendMessage(_a0 message.Message, channel message.MessageChannel) error {
	ret := _m.Called(_a0, channel)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(message.Message, message.MessageChannel) error); ok {
		r0 = rf(_a0, channel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockMessageDispatcher creates a new instance of MockMessageDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageDispatcher {
	mock := &MockMessageDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
