apiVersion: v2
name: sdp
description: A Helm chart for the Stellar Disbursement Platform Backend (A.K.A. `sdp`)

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0-rc1

# This is the version number of the application being deployed. Should be the
# same as the one used in ./main.go#Version.
appVersion: "1.0.0-rc1"
