apiVersion: v2
name: stellar-disbursement-platform
description: A Helm chart for the Stellar Disbursement Platform Backend (A.K.A. `sdp`)
version: 2.0.1
appVersion: "2.0.0"
type: application
maintainers:
  - name: Stellar Development Foundation
sources:
  - https://github.com/stellar/stellar-disbursement-platform-backend
  - https://github.com/stellar/stellar-disbursement-platform-frontend
  - https://github.com/stellar/helm-charts