apiVersion: v2
name: stellar-disbursement-platform
description: A Helm chart for the Stellar Disbursement Platform Backend (A.K.A. `sdp`)
version: 0.9.4
appVersion: "1.0.2"
type: application
maintainers:
  - name: Stellar Development Foundation
sources:
  - https://github.com/stellar/stellar-disbursement-platform-backend
  - https://github.com/stellar/stellar-disbursement-platform-frontend
  - https://github.com/stellar/helm-charts