apiVersion: v2
name: stellar-disbursement-platform
description: A Helm chart for the Stellar Disbursement Platform Backend (A.K.A. `sdp`)
version: "3.7.4"
appVersion: "3.7.3"
type: application
maintainers:
  - name: Stellar Development Foundation
sources:
  - https://github.com/stellar/stellar-disbursement-platform-backend
  - https://github.com/stellar/stellar-disbursement-platform-frontend
  - https://github.com/stellar/helm-charts
