// Code generated by mockery v2.53.5. DO NOT EDIT.

package services

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSEP45Service is an autogenerated mock type for the SEP45Service type
type MockSEP45Service struct {
	mock.Mock
}

// CreateChallenge provides a mock function with given fields: ctx, req
func (_m *MockSEP45Service) CreateChallenge(ctx context.Context, req SEP45ChallengeRequest) (*SEP45ChallengeResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateChallenge")
	}

	var r0 *SEP45ChallengeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, SEP45ChallengeRequest) (*SEP45ChallengeResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, SEP45ChallengeRequest) *SEP45ChallengeResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SEP45ChallengeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, SEP45ChallengeRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateChallenge provides a mock function with given fields: ctx, req
func (_m *MockSEP45Service) ValidateChallenge(ctx context.Context, req SEP45ValidationRequest) (*SEP45ValidationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ValidateChallenge")
	}

	var r0 *SEP45ValidationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, SEP45ValidationRequest) (*SEP45ValidationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, SEP45ValidationRequest) *SEP45ValidationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SEP45ValidationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, SEP45ValidationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSEP45Service creates a new instance of MockSEP45Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSEP45Service(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSEP45Service {
	mock := &MockSEP45Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
