name: E2E integration test action
description: Actions for E2E integration tests

inputs:
    distribution_account_type:
        description: 'The distribution account type to use for the integration tests'
        required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cleanup data
      working-directory: internal/integrationtests
      run: docker-compose -f docker-compose-e2e-tests.yml down -v
      shell: bash

    - name: Run Docker Compose for SDP, Anchor Platform and TSS
      working-directory: internal/integrationtests
      run: docker-compose -f docker-compose-e2e-tests.yml up --build -V -d
      shell: bash

    - name: Install curl
      run: sudo apt-get update && sudo apt-get install -y curl
      shell: bash

    - name: Create integration test data
      run: |
        docker exec e2e-sdp-api bash -c "./stellar-disbursement-platform integration-tests create-data"
      env:
        DISTRIBUTION_ACCOUNT_TYPE: ${{ inputs.distribution_account_type }}
      shell: bash

    - name: Restart anchor platform
      run: |
        docker restart e2e-anchor-platform
      shell: bash

    - name: Wait for anchor platform localhost:8080/health
      run: |
        until curl --output /dev/null --silent --head --fail http://localhost:8080/health; do
          echo 'Waiting for anchor-platform to be up and running...'
          sleep 15
        done
        echo 'Anchor-platform is up and running.'
      shell: bash

    - name: Start integration test command
      run: |
        docker exec e2e-sdp-api bash -c "./stellar-disbursement-platform integration-tests start"
      shell: bash

    - name: Docker logs
      if: always()
      working-directory: internal/integrationtests
      run: docker-compose -f docker-compose-e2e-tests.yml logs && docker-compose -f docker-compose-e2e-tests.yml down
      shell: bash
