{{- if .Values.tss.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdp.fullname" . }}-tss
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labelsWithSuffix" (list . "-tss") | nindent 4 }}

  {{- if .Values.tss.configMap.annotations }}
  annotations:
    {{- toYaml .Values.tss.configMap.annotations | nindent 4 }}
  {{- end }}

data:
  {{- if eq (include "isPubnet" .) "true" }}
  NETWORK_PASSPHRASE: "Public Global Stellar Network ; September 2015"
  HORIZON_URL: "https://horizon.stellar.org"
  {{- else }}
  NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
  HORIZON_URL: "https://horizon-testnet.stellar.org"
  {{- end }}
  TSS_METRICS_PORT: {{ include "tss.metricsPort" . | quote }}
  EVENT_BROKER_TYPE: {{ .Values.global.eventBroker.type | quote }}
  BROKER_URLS: {{ .Values.global.eventBroker.urls | quote }}
  CONSUMER_GROUP_ID: {{ .Values.global.eventBroker.consumerGroupId | quote }}
  {{- if eq .Values.global.eventBroker.type "KAFKA" }}
  KAFKA_SECURITY_PROTOCOL: {{ .Values.global.eventBroker.kafka.securityProtocol | quote }}
  {{- end }}
  {{- tpl (toYaml .Values.tss.configMap.data | nindent 2) . }}
{{- end }}