---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdp.fullname" . }}-tss
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | nindent 4 }}

  {{- if .Values.tss.configMap.annotations }}
  annotations:
    {{- toYaml .Values.tss.configMap.annotations | nindent 4 }}
  {{- end }}

data:
  {{- if eq (include "isPubnet" .) "true" }}
  NETWORK_PASSPHRASE: "Public Global Stellar Network ; September 2015"
  HORIZON_URL: "https://horizon.stellar.org"
  {{- else }}
  NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
  HORIZON_URL: "https://horizon-testnet.stellar.org"
  {{- end }}
  TSS_METRICS_PORT: {{ include "tss.metricsPort" . | quote }}
  {{- tpl (toYaml .Values.tss.configMap.data | nindent 2) . }}
