apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdp.fullname" . }}-ap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labelsWithSuffix" (list . "-ap") | nindent 4 }}
  {{- if .Values.anchorPlatform.deployment.annotations }}
  annotations:
    {{- tpl (toYaml .Values.anchorPlatform.deployment.annotations) . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.global.autoscaling.enabled }}
  replicas: {{ .Values.global.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sdp.selectorLabelsWithSuffix" (list . "-ap") | nindent 6 }}

  {{- if .Values.anchorPlatform.deployment.strategy }}
  strategy:
    {{- toYaml .Values.anchorPlatform.deployment.strategy | nindent 4 }}
  {{- end }}
  
  template:
    metadata:
      {{- if .Values.anchorPlatform.deployment.podAnnotations }}
      annotations:
        {{- tpl (toYaml .Values.anchorPlatform.deployment.podAnnotations) . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sdp.selectorLabelsWithSuffix" (list . "-ap") | nindent 8 }}
    spec:
      # {{- if .Values.global.serviceAccount.name }}
      # serviceAccountName: {{ tpl .Values.global.serviceAccount.name $ }}
      # {{- end }}
      {{- if or .Values.anchorPlatform.deployment.priorityClassName .Values.global.deployment.priorityClassName }}
      priorityClassName: {{ .Values.anchorPlatform.deployment.priorityClassName | default .Values.global.deployment.priorityClassName | quote }}
      {{- end }}
      securityContext:
        {{- tpl (toYaml .Values.anchorPlatform.deployment.podSecurityContext) . | nindent 8 }}
      
      {{- with default .Values.global.deployment.topologySpreadConstraints .Values.anchorPlatform.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      containers:
      # ============================= Anchor Platform: =============================
        - name: {{ .Chart.Name }}-ap
          securityContext:
            {{- tpl (toYaml .Values.anchorPlatform.deployment.securityContext) . | nindent 12 }}
          image: "{{ .Values.anchorPlatform.image.repository }}:{{ .Values.anchorPlatform.image.tag }}"
          imagePullPolicy: {{ .Values.anchorPlatform.image.pullPolicy }}
          {{- if .Values.global.ephemeralDatabase }}
          env:
            - name: DATA_TYPE
              value: 'postgres'
            - name: DATA_SERVER
              value: '{{ include "sdp.fullname" . }}-psql.{{ .Release.Namespace }}.svc.cluster.local:5433'
            - name: DATA_DATABASE
              value: 'postgres-ap'
            - name: SECRET_DATA_USERNAME
              value: 'postgres'
            - name: SECRET_DATA_PASSWORD
              value: 'postgres'
            - name: SDP_IMAGE_TAG  # This env is used to force the AP to be redeployed every time the SDP is deployed. This is used to force the SDP to re-fetch the toml file and assets to ensure the latest ones are used.
              value: {{ .Values.sdp.image.tag }}
          {{- end }}
          args:
            - "--sep-server"
            - "--platform-server"
          ports:
            - name: ap-sep
              containerPort: {{ include "sdp.ap.sepPort" . }}
              protocol: TCP
            - name: ap-platform
              containerPort: {{ include "sdp.ap.platformPort" . }}
              protocol: TCP
            - name: ap-metrics
              containerPort: {{ include "sdp.ap.metricsPort" . }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health?checks=config
              port: ap-sep
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health?checks=config
              port: ap-sep
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 10
          startupProbe:
            httpGet:
              path: /health?checks=config
              port: ap-sep
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 10

          {{- if .Values.anchorPlatform.deployment.resources }}
          resources:
            {{- tpl (toYaml .Values.anchorPlatform.deployment.resources) . | nindent 12 }}
          {{- end }}

          envFrom:
          - configMapRef:
              name: {{ include "sdp.fullname" . }}-ap
          
          {{- if .Values.anchorPlatform.kubeSecrets.secretName }}
          - secretRef:
              name: {{ .Values.anchorPlatform.kubeSecrets.secretName }}
          {{ end }}

      {{- with .Values.anchorPlatform.deployment.nodeSelector | default .Values.global.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anchorPlatform.deployment.affinity | default .Values.global.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anchorPlatform.deployment.tolerations | default .Values.global.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
