{{- if .Values.tss.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdp.fullname" . }}-tss
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labelsWithSuffix" (list . "-tss") | nindent 4 }}
spec:
  type: {{ .Values.global.service.type }}
  ports:
    - port: {{ include "tss.metricsPort" . }}
      targetPort: metrics
      protocol: TCP
      name: metrics

  selector:
    {{- include "sdp.selectorLabelsWithSuffix" (list . "-tss") | nindent 4 }}
{{- end }}
