{{- if .Values.global.enableAnchorPlatform }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdp.fullname" . }}-ap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labelsWithSuffix" (list . "-ap") | nindent 4 }}
spec:
  type: {{ .Values.global.service.type }}
  ports:
    - port: {{ include "sdp.ap.sepPort" . }}
      targetPort: ap-sep
      protocol: TCP
      name: ap-sep
    - port: {{ include "sdp.ap.platformPort" . }}
      targetPort: ap-platform
      protocol: TCP
      name: ap-platform
    
  selector:
    {{- include "sdp.selectorLabelsWithSuffix" (list . "-ap") | nindent 4 }}
{{- end }}
