apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdp.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - port: {{ include "sdp.metricsPort" . }}
      targetPort: metrics
      protocol: TCP
      name: metrics

  selector:
    {{- include "sdp.selectorLabels" . | nindent 4 }}
