{{- if .Values.anchorPlatform.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sdp.fullname" . }}-ap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.anchorPlatform.ingress.annotations | nindent 4 }}
    # This is a way to block the stellar.toml file from being served on the "sdp.domain":
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~ /.well-known/stellar.toml {
        proxy_pass {{ include "sdp.ap.sepServiceAddress" . }};
      }
spec:
  {{- if .Values.anchorPlatform.ingress.className }}
  ingressClassName: {{ .Values.anchorPlatform.ingress.className }}
  {{- end }}
  {{- if .Values.anchorPlatform.ingress.tls }}
  tls:
    {{- tpl (toYaml .Values.anchorPlatform.ingress.tls) . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ include "sdp.ap.domain" . | quote }}
      http:
        paths:
          # Only enable the AP endpints that are needed for this application:
          {{- $service_name := printf "%s-ap" (include "sdp.fullname" .) }}
          {{- $service_sep_port := include "sdp.ap.sepPort" . }}
          {{- $paths := list "/health" "/.well-known" "/auth" "/sep24" -}}
          {{- range $path := $paths }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $service_name }}
                port:
                  number: {{ $service_sep_port }}
          {{- end }}
{{- end }}
