{{- if .Values.sdp.kubeSecrets.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | nindent 4 }}

  {{- if .Values.sdp.kubeSecrets.annotations }}
  annotations:
    {{- toYaml .Values.sdp.kubeSecrets.annotations | nindent 4 }}
  {{- end }}

{{- if .Values.sdp.kubeSecrets.data }}
data:
  {{- range $key, $value := .Values.sdp.kubeSecrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}