{{- if .Values.sdp.kubeSecrets.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | nindent 4 }}

  {{- if .Values.sdp.kubeSecrets.annotations }}
  annotations:
    {{- toYaml .Values.sdp.kubeSecrets.annotations | nindent 4 }}
  {{- end }}

data:
  {{- /* EC256_PRIVATE_KEY */ -}}
  {{- if or .Values.global.autoGenerateSecrets .Values.sdp.kubeSecrets.data.EC256_PRIVATE_KEY }}
  EC256_PRIVATE_KEY: {{ default (include "sdp.ec256PrivateKey" . | b64enc) .Values.sdp.kubeSecrets.data.EC256_PRIVATE_KEY | quote }}
  {{- else }}
  {{- required "sdp.kubeSecrets.data.EC256_PRIVATE_KEY is required" .Values.sdp.kubeSecrets.data.EC256_PRIVATE_KEY }}
  {{- end }}

  {{- /* ADMIN_ACCOUNT */ -}}
  {{- if or .Values.global.autoGenerateSecrets .Values.sdp.kubeSecrets.data.ADMIN_ACCOUNT }}
  ADMIN_ACCOUNT: {{ default (include "sdp.adminAccount" . | b64enc) .Values.sdp.kubeSecrets.data.ADMIN_ACCOUNT | quote }}
  {{- else }}
  {{- required "sdp.kubeSecrets.data.ADMIN_ACCOUNT is required" .Values.sdp.kubeSecrets.data.ADMIN_ACCOUNT }}
  {{- end }}

  {{- /* ADMIN_API_KEY */ -}}
  {{- if or .Values.global.autoGenerateSecrets .Values.sdp.kubeSecrets.data.ADMIN_API_KEY }}
  ADMIN_API_KEY: {{ default (include "sdp.adminApiKey" . | b64enc) .Values.sdp.kubeSecrets.data.ADMIN_API_KEY | quote }}
  {{- else }}
  {{- required "sdp.kubeSecrets.data.ADMIN_API_KEY is required" .Values.sdp.kubeSecrets.data.ADMIN_API_KEY }}
  {{- end }}


  {{- /* SEP24_JWT_SECRET */ -}}
  {{- if or .Values.global.autoGenerateSecrets .Values.sdp.kubeSecrets.data.SEP24_JWT_SECRET }}
  SEP24_JWT_SECRET: {{ default (include "sdp.jwtSecret" . | b64enc) .Values.sdp.kubeSecrets.data.SEP24_JWT_SECRET | quote }}
  {{- else }}
  {{- required "sdp.kubeSecrets.data.SEP24_JWT_SECRET is required" .Values.sdp.kubeSecrets.data.SEP24_JWT_SECRET }}
  {{- end }}

  {{- /* ANCHOR_PLATFORM_OUTGOING_JWT_SECRET */ -}}
  {{- if or .Values.global.autoGenerateSecrets .Values.sdp.kubeSecrets.data.ANCHOR_PLATFORM_OUTGOING_JWT_SECRET }}
  ANCHOR_PLATFORM_OUTGOING_JWT_SECRET: {{ default (include "sdp.platformAuthSecret" . | b64enc) .Values.sdp.kubeSecrets.data.ANCHOR_PLATFORM_OUTGOING_JWT_SECRET | quote }}
  {{- else }}
  {{- required "sdp.kubeSecrets.data.ANCHOR_PLATFORM_OUTGOING_JWT_SECRET is required" .Values.sdp.kubeSecrets.data.ANCHOR_PLATFORM_OUTGOING_JWT_SECRET }}
  {{- end }}

{{- /*
Values from the global section
  */}}
  {{- if .Values.global.distributionPrivateKey }}
  DISTRIBUTION_SEED: {{ .Values.global.distributionPrivateKey | b64enc | quote }}
    {{- if not .Values.sdp.kubeSecrets.data.DISTRIBUTION_ACCOUNT_ENCRYPTION_PASSPHRASE }}
  DISTRIBUTION_ACCOUNT_ENCRYPTION_PASSPHRASE: {{ .Values.global.distributionPrivateKey | b64enc | quote }}
    {{- end }}
    {{- if not .Values.sdp.kubeSecrets.data.CHANNEL_ACCOUNT_ENCRYPTION_PASSPHRASE }}
  CHANNEL_ACCOUNT_ENCRYPTION_PASSPHRASE: {{ .Values.global.distributionPrivateKey | b64enc | quote }}
    {{- end }}
  {{- end }}

  {{- if .Values.global.recaptchaSiteSecretKey  }}
  RECAPTCHA_SITE_SECRET_KEY: {{ .Values.global.recaptchaSiteSecretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.sep10PrivateKey }}
  SEP10_SIGNING_PRIVATE_KEY: {{ .Values.global.sep10PrivateKey | b64enc | quote }}
  {{- end }}

  {{- /*
Values from the sdp secrets section - These will override the template values
  */}}
  {{- range $key, $value := .Values.sdp.kubeSecrets.data }}
    {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}