{{- if .Values.sdp.kubeSecrets.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | nindent 4 }}

  {{- if .Values.sdp.kubeSecrets.annotations }}
  annotations:
    {{- toYaml .Values.sdp.kubeSecrets.annotations | nindent 4 }}
  {{- end }}

data:
  {{- if not .Values.sdp.kubeSecrets.data.EC256_PRIVATE_KEY }}
  EC256_PRIVATE_KEY: {{ include "sdp.ec256PrivateKey" . | b64enc | quote }}
  {{- end }}
  {{- if not .Values.sdp.kubeSecrets.data.ADMIN_ACCOUNT }}
  ADMIN_ACCOUNT: {{ include "sdp.adminAccount" . | b64enc | quote }}
  {{- end }}
  {{- if not .Values.sdp.kubeSecrets.data.ADMIN_API_KEY }}
  ADMIN_API_KEY: {{ include "sdp.adminApiKey" . | b64enc | quote }}
  {{- end }}
  {{- $jwtSecret := include "sdp.jwtSecret" . -}}
  {{- if not .Values.sdp.kubeSecrets.data.SEP24_JWT_SECRET }}
  SEP24_JWT_SECRET: {{ $jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if not .Values.sdp.kubeSecrets.data.ANCHOR_PLATFORM_OUTGOING_JWT_SECRET }}
  ANCHOR_PLATFORM_OUTGOING_JWT_SECRET: {{ include "sdp.platformAuthSecret" . | b64enc | quote }}
  {{- end }}
{{- /*
Values from the global section
  */}}
  {{- if .Values.global.distributionPrivateKey }}
  DISTRIBUTION_SEED: {{ .Values.global.distributionPrivateKey | b64enc | quote }}
  DISTRIBUTION_ACCOUNT_ENCRYPTION_PASSPHRASE: {{ .Values.global.distributionPrivateKey | b64enc | quote }}
  CHANNEL_ACCOUNT_ENCRYPTION_PASSPHRASE: {{ .Values.global.distributionPrivateKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.recaptchaSiteSecretKey }}
  RECAPTCHA_SITE_SECRET_KEY: {{ .Values.global.recaptchaSiteSecretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.sep10PrivateKey }}
  SEP10_SIGNING_PRIVATE_KEY: {{ .Values.global.sep10PrivateKey | b64enc | quote }}
  {{- end }}
  {{- /*
Values from the sdp secrets section - These will override the template values
  */}}
  {{- range $key, $value := .Values.sdp.kubeSecrets.data }}
    {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}