{{- if and .Values.global.enableAnchorPlatform .Values.anchorPlatform.kubeSecrets.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdp.fullname" . }}-ap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | nindent 4 }}

  {{- if .Values.anchorPlatform.kubeSecrets.annotations }}
  annotations:
    {{- toYaml .Values.anchorPlatform.kubeSecrets.annotations | nindent 4 }}
  {{- end }}

data:
  {{- /* SECRET_PLATFORM_API_AUTH_SECRET */ -}}
  {{- if or .Values.global.autoGenerateSecrets .Values.anchorPlatform.kubeSecrets.data.SECRET_PLATFORM_API_AUTH_SECRET }}
  SECRET_PLATFORM_API_AUTH_SECRET: {{ default (include "sdp.platformAuthSecret" . | b64enc) .Values.anchorPlatform.kubeSecrets.data.SECRET_PLATFORM_API_AUTH_SECRET | quote }}
  {{- else }}
  {{- required "anchorPlatform.kubeSecrets.data.SECRET_PLATFORM_API_AUTH_SECRET is required" .Values.anchorPlatform.kubeSecrets.data.SECRET_PLATFORM_API_AUTH_SECRET }}
  {{- end }}

  {{- $jwtSecret := include "sdp.jwtSecret" . -}}
  {{- /* SECRET_SEP10_JWT_SECRET */ -}}
  {{- if or .Values.global.autoGenerateSecrets .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP10_JWT_SECRET }}
  SECRET_SEP10_JWT_SECRET: {{ default ($jwtSecret | b64enc) .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP10_JWT_SECRET | quote }}
  {{- else }}
  {{- required "anchorPlatform.kubeSecrets.data.SECRET_SEP10_JWT_SECRET is required" .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP10_JWT_SECRET }}
  {{- end }}

  {{- /* SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET */ -}}
  {{- if or .Values.global.autoGenerateSecrets .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET }}
  SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET: {{ default ($jwtSecret | b64enc) .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET | quote }}
  {{- else }}
  {{- required "anchorPlatform.kubeSecrets.data.SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET is required" .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET }}
  {{- end }}

  {{- /* SECRET_SEP24_MORE_INFO_URL_JWT_SECRET */ -}}
  {{- if or .Values.global.autoGenerateSecrets .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP24_MORE_INFO_URL_JWT_SECRET }}
  SECRET_SEP24_MORE_INFO_URL_JWT_SECRET: {{ default ($jwtSecret | b64enc) .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP24_MORE_INFO_URL_JWT_SECRET | quote }}
  {{- else }}
  {{- required "anchorPlatform.kubeSecrets.data.SECRET_SEP24_MORE_INFO_URL_JWT_SECRET is required" .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP24_MORE_INFO_URL_JWT_SECRET }}
  {{- end }}

{{- /*
Values from the global section
  */}}
  {{- if .Values.global.sep10PrivateKey }}
  SECRET_SEP10_SIGNING_SEED: {{ .Values.global.sep10PrivateKey | b64enc | quote }}
  {{- end }}

  {{- /*
Values from the ap secrets section - These will override the template values
  */}}
  {{- range $key, $value := .Values.tss.kubeSecrets.data }}
    {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}