{{- if .Values.anchorPlatform.kubeSecrets.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdp.fullname" . }}-ap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | nindent 4 }}

  {{- if .Values.anchorPlatform.kubeSecrets.annotations }}
  annotations:
    {{- toYaml .Values.anchorPlatform.kubeSecrets.annotations | nindent 4 }}
  {{- end }}

data:
  {{- $jwtSecret := include "sdp.jwtSecret" . -}}
  {{- if not .Values.anchorPlatform.kubeSecrets.data.SECRET_PLATFORM_API_AUTH_SECRET }}
  SECRET_PLATFORM_API_AUTH_SECRET: {{ include "sdp.platformAuthSecret" . | b64enc | quote }}
  {{- end }}
  {{- if not .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP10_JWT_SECRET }}
  SECRET_SEP10_JWT_SECRET: {{ $jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if not .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET }}
  SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET: {{ $jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if not .Values.anchorPlatform.kubeSecrets.data.SECRET_SEP24_MORE_INFO_URL_JWT_SECRET }}
  SECRET_SEP24_MORE_INFO_URL_JWT_SECRET: {{ $jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.sep10PrivateKey }}
  SECRET_SEP10_SIGNING_SEED: {{ .Values.global.sep10PrivateKey | b64enc | quote }}
  {{- end }}
  {{- /*
Values from the ap secrets section - These will override the template values
  */}}
  {{- range $key, $value := .Values.tss.kubeSecrets.data }}
    {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}