{{- if .Values.anchorPlatform.kubeSecrets.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdp.fullname" . }}-ap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | nindent 4 }}

  {{- if .Values.anchorPlatform.kubeSecrets.annotations }}
  annotations:
    {{- toYaml .Values.anchorPlatform.kubeSecrets.annotations | nindent 4 }}
  {{- end }}

{{- if .Values.anchorPlatform.kubeSecrets.data }}
data:
  {{- range $key, $value := .Values.anchorPlatform.kubeSecrets.data }}
    {{- if $value }}
      {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}