// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	data "github.com/stellar/stellar-disbursement-platform-backend/internal/data"
	mock "github.com/stretchr/testify/mock"
)

// MockEmbeddedWalletService is an autogenerated mock type for the EmbeddedWalletServiceInterface type
type MockEmbeddedWalletService struct {
	mock.Mock
}

// CreateInvitationToken provides a mock function with given fields: ctx
func (_m *MockEmbeddedWalletService) CreateInvitationToken(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitationToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateWallet provides a mock function with given fields: ctx, token, publicKey, credentialID
func (_m *MockEmbeddedWalletService) CreateWallet(ctx context.Context, token string, publicKey string, credentialID string) error {
	ret := _m.Called(ctx, token, publicKey, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, token, publicKey, credentialID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPendingDisbursementAsset provides a mock function with given fields: ctx, contractAddress
func (_m *MockEmbeddedWalletService) GetPendingDisbursementAsset(ctx context.Context, contractAddress string) (*data.Asset, error) {
	ret := _m.Called(ctx, contractAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingDisbursementAsset")
	}

	var r0 *data.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*data.Asset, error)); ok {
		return rf(ctx, contractAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *data.Asset); ok {
		r0 = rf(ctx, contractAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, contractAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReceiverContact provides a mock function with given fields: ctx, contractAddress
func (_m *MockEmbeddedWalletService) GetReceiverContact(ctx context.Context, contractAddress string) (*data.Receiver, error) {
	ret := _m.Called(ctx, contractAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetReceiverContact")
	}

	var r0 *data.Receiver
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*data.Receiver, error)); ok {
		return rf(ctx, contractAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *data.Receiver); ok {
		r0 = rf(ctx, contractAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Receiver)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, contractAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionStatus provides a mock function with given fields: ctx, account, transactionID
func (_m *MockEmbeddedWalletService) GetTransactionStatus(ctx context.Context, account string, transactionID string) (*data.SponsoredTransaction, error) {
	ret := _m.Called(ctx, account, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionStatus")
	}

	var r0 *data.SponsoredTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*data.SponsoredTransaction, error)); ok {
		return rf(ctx, account, transactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *data.SponsoredTransaction); ok {
		r0 = rf(ctx, account, transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.SponsoredTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, account, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletByCredentialID provides a mock function with given fields: ctx, credentialID
func (_m *MockEmbeddedWalletService) GetWalletByCredentialID(ctx context.Context, credentialID string) (*data.EmbeddedWallet, error) {
	ret := _m.Called(ctx, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletByCredentialID")
	}

	var r0 *data.EmbeddedWallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*data.EmbeddedWallet, error)); ok {
		return rf(ctx, credentialID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *data.EmbeddedWallet); ok {
		r0 = rf(ctx, credentialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.EmbeddedWallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, credentialID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsVerificationPending provides a mock function with given fields: ctx, contractAddress
func (_m *MockEmbeddedWalletService) IsVerificationPending(ctx context.Context, contractAddress string) (bool, error) {
	ret := _m.Called(ctx, contractAddress)

	if len(ret) == 0 {
		panic("no return value specified for IsVerificationPending")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, contractAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, contractAddress)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, contractAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SponsorTransaction provides a mock function with given fields: ctx, account, operationXDR
func (_m *MockEmbeddedWalletService) SponsorTransaction(ctx context.Context, account string, operationXDR string) (string, error) {
	ret := _m.Called(ctx, account, operationXDR)

	if len(ret) == 0 {
		panic("no return value specified for SponsorTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, account, operationXDR)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, account, operationXDR)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, account, operationXDR)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockEmbeddedWalletService creates a new instance of MockEmbeddedWalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddedWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddedWalletService {
	mock := &MockEmbeddedWalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
