// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	data "github.com/stellar/stellar-disbursement-platform-backend/internal/data"
	mock "github.com/stretchr/testify/mock"
)

// MockEmbeddedWalletService is an autogenerated mock type for the EmbeddedWalletServiceInterface type
type MockEmbeddedWalletService struct {
	mock.Mock
}

// CreateInvitationToken provides a mock function with given fields: ctx, receiverContact, contactType, receiverID
func (_m *MockEmbeddedWalletService) CreateInvitationToken(ctx context.Context, receiverContact string, contactType string, receiverID string) (string, error) {
	ret := _m.Called(ctx, receiverContact, contactType, receiverID)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitationToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, receiverContact, contactType, receiverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, receiverContact, contactType, receiverID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, receiverContact, contactType, receiverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateWallet provides a mock function with given fields: ctx, token, publicKey, credentialID
func (_m *MockEmbeddedWalletService) CreateWallet(ctx context.Context, token string, publicKey string, credentialID string) error {
	ret := _m.Called(ctx, token, publicKey, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, token, publicKey, credentialID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWalletByCredentialID provides a mock function with given fields: ctx, credentialID
func (_m *MockEmbeddedWalletService) GetWalletByCredentialID(ctx context.Context, credentialID string) (*data.EmbeddedWallet, error) {
	ret := _m.Called(ctx, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletByCredentialID")
	}

	var r0 *data.EmbeddedWallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*data.EmbeddedWallet, error)); ok {
		return rf(ctx, credentialID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *data.EmbeddedWallet); ok {
		r0 = rf(ctx, credentialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.EmbeddedWallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, credentialID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletByReceiverContact provides a mock function with given fields: ctx, receiverContact, contactType
func (_m *MockEmbeddedWalletService) GetWalletByReceiverContact(ctx context.Context, receiverContact string, contactType string) (*data.EmbeddedWallet, error) {
	ret := _m.Called(ctx, receiverContact, contactType)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletByReceiverContact")
	}

	var r0 *data.EmbeddedWallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*data.EmbeddedWallet, error)); ok {
		return rf(ctx, receiverContact, contactType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *data.EmbeddedWallet); ok {
		r0 = rf(ctx, receiverContact, contactType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.EmbeddedWallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, receiverContact, contactType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletByToken provides a mock function with given fields: ctx, token
func (_m *MockEmbeddedWalletService) GetWalletByToken(ctx context.Context, token string) (*data.EmbeddedWallet, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletByToken")
	}

	var r0 *data.EmbeddedWallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*data.EmbeddedWallet, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *data.EmbeddedWallet); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.EmbeddedWallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResendInvite provides a mock function with given fields: ctx, receiverContact, contactType
func (_m *MockEmbeddedWalletService) ResendInvite(ctx context.Context, receiverContact string, contactType string) error {
	ret := _m.Called(ctx, receiverContact, contactType)

	if len(ret) == 0 {
		panic("no return value specified for ResendInvite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, receiverContact, contactType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockEmbeddedWalletService creates a new instance of MockEmbeddedWalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddedWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddedWalletService {
	mock := &MockEmbeddedWalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
