// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNonceStore is an autogenerated mock type for the NonceStoreInterface type
type MockNonceStore struct {
	mock.Mock
}

// Consume provides a mock function with given fields: ctx, nonce
func (_m *MockNonceStore) Consume(ctx context.Context, nonce string) (bool, error) {
	ret := _m.Called(ctx, nonce)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, nonce)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, nonce)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nonce)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, nonce
func (_m *MockNonceStore) Store(ctx context.Context, nonce string) error {
	ret := _m.Called(ctx, nonce)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, nonce)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockNonceStore creates a new instance of MockNonceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNonceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNonceStore {
	mock := &MockNonceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
