// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSponsoredTransactionsToSubmitterService is an autogenerated mock type for the SponsoredTransactionsToSubmitterServiceInterface type
type MockSponsoredTransactionsToSubmitterService struct {
	mock.Mock
}

// SendBatchSponsoredTransactions provides a mock function with given fields: ctx, batchSize
func (_m *MockSponsoredTransactionsToSubmitterService) SendBatchSponsoredTransactions(ctx context.Context, batchSize int) error {
	ret := _m.Called(ctx, batchSize)

	if len(ret) == 0 {
		panic("no return value specified for SendBatchSponsoredTransactions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, batchSize)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSponsoredTransactionsToSubmitterService creates a new instance of MockSponsoredTransactionsToSubmitterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSponsoredTransactionsToSubmitterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSponsoredTransactionsToSubmitterService {
	mock := &MockSponsoredTransactionsToSubmitterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
