// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletCreationToSubmitterService is an autogenerated mock type for the WalletCreationToSubmitterServiceInterface type
type MockWalletCreationToSubmitterService struct {
	mock.Mock
}

// SendBatchWalletCreations provides a mock function with given fields: ctx, batchSize
func (_m *MockWalletCreationToSubmitterService) SendBatchWalletCreations(ctx context.Context, batchSize int) error {
	ret := _m.Called(ctx, batchSize)

	if len(ret) == 0 {
		panic("no return value specified for SendBatchWalletCreations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, batchSize)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockWalletCreationToSubmitterService creates a new instance of MockWalletCreationToSubmitterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletCreationToSubmitterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletCreationToSubmitterService {
	mock := &MockWalletCreationToSubmitterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
