// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DistributionAccountResolver is an autogenerated mock type for the DistributionAccountResolver type
type DistributionAccountResolver struct {
	mock.Mock
}

// DistributionAccount provides a mock function with given fields:
func (_m *DistributionAccountResolver) DistributionAccount() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// HostDistributionAccount provides a mock function with given fields:
func (_m *DistributionAccountResolver) HostDistributionAccount() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewDistributionAccountResolver interface {
	mock.TestingT
	Cleanup(func())
}

// NewDistributionAccountResolver creates a new instance of DistributionAccountResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDistributionAccountResolver(t mockConstructorTestingTNewDistributionAccountResolver) *DistributionAccountResolver {
	mock := &DistributionAccountResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
