{
 "title": "Dashboard SDPV2",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "route",
    "query": {
     "query": "query_result(sdp_http_requests_duration_seconds_count)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "query_result(sdp_http_requests_duration_seconds_count)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "query_result(sdp_http_requests_duration_seconds_count)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "query_result(sdp_http_requests_duration_seconds_count)"
    }
   },
   {
    "name": "query_type",
    "label": "query_type",
    "query": {
     "query": "query_result(sdp_db_failure_queries_duration_count or sdp_db_successful_queries_duration_count)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Http Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate [5m]",
     "type": "timeseries",
     "description": "Rate request per second in a 5 min interval. Filtered by route, method, status and instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(sdp_http_requests_duration_seconds_count{route=~\"$route\", method=~\"$method\", status=~\"$status\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{method}} {{route}}: {{status}} {{instance}}"
      }
     ]
    },
    {
     "title": "Avg Request Duration [5m]",
     "type": "timeseries",
     "description": "Average request time duration in a 5 min interval. Filtered by route, method, status and instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "1000 * (rate(sdp_http_requests_duration_seconds_sum{route=~\"$route\", method=~\"$method\", status=~\"$status\", instance=~\"$instance\"}[5m]) / rate(sdp_http_requests_duration_seconds_count{route=~\"$route\", method=~\"$method\", status=~\"$status\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{method}} {{route}}: {{status}} {{instance}}"
      }
     ]
    },
    {
     "title": "Request Rate Aggregate by Instance [5m]",
     "type": "timeseries",
     "description": "Average rate request per second in a 5 min interval aggregate by instance. Filtered by route, method, status.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "avg(rate(sdp_http_requests_duration_seconds_count{route=~\"$route\", method=~\"$method\", status=~\"$status\", instance=~\"$instance\"}[5m])) by (route, method, status)",
       "legendFormat": "{{method}} {{route}}: {{status}}"
      }
     ]
    },
    {
     "title": "Avg Request Duration Aggregate by instances [5m]",
     "type": "timeseries",
     "description": "Average request time duration in a 5 min interval aggregate by instances. Filtered by route, method, status.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "1000 * avg((rate(sdp_http_requests_duration_seconds_sum{route=~\"$route\", method=~\"$method\", status=~\"$status\", instance=~\"$instance\"}[5m]) / rate(sdp_http_requests_duration_seconds_count{route=~\"$route\", method=~\"$method\", status=~\"$status\", instance=~\"$instance\"}[5m]))) by (route, method, status)",
       "legendFormat": "{{method}} {{route}}: {{status}}"
      }
     ]
    },
    {
     "title": "Http Request Quantile",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "1000 * sdp_http_requests_duration_seconds{route=~\"$route\", method=~\"$method\", status=~\"$status\", instance=~\"$instance\"}",
       "legendFormat": "q{{quantile}} {{method}} {{route}}: {{status}} {{instance}}"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "stat",
     "description": "Total number of requests filtered by route, method, status and instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sdp_http_requests_duration_seconds_count{route=~\"$route\", method=~\"$method\", status=~\"$status\", instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Avg Request Time Duration [ms]",
     "type": "stat",
     "description": "Total average time duration from a request. Filtered by route, method, status and instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1000 * avg(sdp_http_requests_duration_seconds_sum{route=~\"$route\", method=~\"$method\", status=~\"$status\", instance=~\"$instance\"} / sdp_http_requests_duration_seconds_count{route=~\"$route\", method=~\"$method\", status=~\"$status\", instance=~\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Query Rate [5m]",
     "type": "timeseries",
     "description": "Rate successful query per second in a 5 min interval. Filtered by query_type and instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(sdp_db_successful_queries_duration_count{query_type=~\"$query_type\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{query_type}} {{instance}}"
      }
     ]
    },
    {
     "title": "Avg Successful Query Duration [5m]",
     "type": "timeseries",
     "description": "Average successful query duration in a 5 min interval. Filtered by query_type and instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "1000 * (rate(sdp_db_successful_queries_duration_sum{query_type=~\"$query_type\", instance=~\"$instance\"}[5m]) / rate(sdp_db_successful_queries_duration_count{query_type=~\"$query_type\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{query_type}} {{instance}}"
      }
     ]
    },
    {
     "title": "Successful Query Rate Aggregate By Instances [5m]",
     "type": "timeseries",
     "description": "Average rate successful query per second in a 5 min interval. Filtered by query_type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "avg(rate(sdp_db_successful_queries_duration_count{query_type=~\"$query_type\", instance=~\"$instance\"}[5m])) by (query_type)",
       "legendFormat": "{{query_type}}"
      }
     ]
    },
    {
     "title": "Avg Succesful Query Duration Aggregate By Instances[5m]",
     "type": "timeseries",
     "description": "Average successful query duration in a 5 min interval aggregate by instances. Filtered by query_type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "avg(1000 * (rate(sdp_db_successful_queries_duration_sum{query_type=~\"$query_type\", instance=~\"$instance\"}[5m]) / rate(sdp_db_successful_queries_duration_count{query_type=~\"$query_type\", instance=~\"$instance\"}[5m]))) by (query_type)",
       "legendFormat": "{{query_type}}"
      }
     ]
    },
    {
     "title": "Successful Query Quantiles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "1000 * sdp_db_successful_queries_duration{query_type=~\"$query_type\", instance=~\"$instance\"}",
       "legendFormat": "q{{quantile}} {{query_type}} {{instance}}"
      }
     ]
    },
    {
     "title": "Failure Query Rate [5m]",
     "type": "timeseries",
     "description": "Rate failure query per second in a 5 min interval. Filtered by query_type and instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(sdp_db_failure_queries_duration_count{query_type=~\"$query_type\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{query_type}} {{instance}}"
      }
     ]
    },
    {
     "title": "Avg Failure Query Duration [5m]",
     "type": "timeseries",
     "description": "Average failure query duration in a 5 min interval. Filtered by query_type and instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "1000 * (rate(sdp_db_failure_queries_duration_sum{query_type=~\"$query_type\", instance=~\"$instance\"}[5m]) / rate(sdp_db_failure_queries_duration_count{query_type=~\"$query_type\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{query_type}} {{instance}}"
      }
     ]
    },
    {
     "title": "Failure Query Rate Aggregate By Instances [5m]",
     "type": "timeseries",
     "description": "Average rate failure query per second in a 5 min interval. Filtered by query_type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "avg(rate(sdp_db_failure_queries_duration_count{query_type=~\"$query_type\", instance=~\"$instance\"}[5m])) by (query_type)",
       "legendFormat": "{{query_type}}"
      }
     ]
    },
    {
     "title": "Avg Failure Query Duration Aggregate By Instances[5m]",
     "type": "timeseries",
     "description": "Average failure query duration in a 5 min interval aggregate by instances. Filtered by query_type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "avg(1000 * (rate(sdp_db_failure_queries_duration_sum{query_type=~\"$query_type\", instance=~\"$instance\"}[5m]) / rate(sdp_db_failure_queries_duration_count{query_type=~\"$query_type\", instance=~\"$instance\"}[5m]))) by (query_type)",
       "legendFormat": "{{query_type}}"
      }
     ]
    },
    {
     "title": "Failure Query Quantiles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "1000 * sdp_db_failure_queries_duration{query_type=~\"$query_type\", instance=~\"$instance\"}",
       "legendFormat": "q{{quantile}} {{query_type}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cicle Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Circle API - Error Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (sum(sdp_circle_circle_api_requests_total{status=\"error\"}) \n/\nsum(sdp_circle_circle_api_requests_total)\nor vector(0))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "Circle API - Request Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sdp_circle_circle_api_requests_total)",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "Circle API - 95th Percentile Request Duration by Endpoint and Method",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, endpoint, method) (rate(sdp_circle_circle_api_request_duration_seconds_bucket[1m]) or vector(0)) ) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Circle API - Average Request Duration by Method and Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(sdp_circle_circle_api_request_duration_seconds_sum[5m])) by (endpoint,method) / sum(rate(sdp_circle_circle_api_request_duration_seconds_count[5m])) by (endpoint,method)",
       "legendFormat": "{{method, endpoint}}"
      }
     ]
    },
    {
     "title": "Circle API - Histogram of Request Durations",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum by (le, endpoint, method) (rate(sdp_circle_circle_api_request_duration_seconds_bucket[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}