{
 "title": "Transaction Submission Service Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transactions Processed (Success)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tss_tx_processing_processed_count{result=\"success\"}"
    }
   ]
  },
  {
   "title": "Transactions Processed (Errors)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tss_tx_processing_processed_count{result=\"error\"}"
    }
   ]
  },
  {
   "title": "Log (Errors)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tss_log_error_total" }
   ]
  },
  {
   "title": "Log (Errors)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tss_log_error_total" }
   ]
  },
  {
   "title": "(TODO) - Horizon (Errors)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tss_log_warn_total" }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  sum without (instance)(rate(tss_tx_processing_queued_to_completed_latency_seconds_sum{result=\"success\"}[$__rate_interval\n]))\n/\n  sum without (instance)(rate(tss_tx_processing_queued_to_completed_latency_seconds_count{result=\"success\"}[$__rate_interval\n]))",
     "legendFormat": "latency (since createAt) - {{result}}"
    },
    {
     "expr": "  sum without (instance)(rate(tss_tx_processing_started_to_completed_latency_seconds_sum{result=\"success\"}[$__rate_interval\n]))\n/\n  sum without (instance)(rate(tss_tx_processing_started_to_completed_latency_seconds_count{result=\"success\"}[$__rate_interval\n]))",
     "legendFormat": "latency (since startedAt) - {{result}}"
    }
   ]
  },
  {
   "title": "Transactions Retried (Attempts) Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tss_tx_processing_retry_count_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tss_tx_processing_retry_count_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tss_tx_processing_retry_count_bucket[$__rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tss_tx_processing_retry_count_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Transaction Latency (Queued to Completed) Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tss_tx_processing_queued_to_completed_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tss_tx_processing_queued_to_completed_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tss_tx_processing_queued_to_completed_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tss_tx_processing_queued_to_completed_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Transaction Latency (Started to Completed) Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tss_tx_processing_started_to_completed_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tss_tx_processing_started_to_completed_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tss_tx_processing_started_to_completed_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tss_tx_processing_started_to_completed_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "(TODO) - Transaction Submission Error Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "(TODO) - Horizon Error Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "Goroutine Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "targets": [
    { "expr": "go_goroutines" }
   ]
  }
 ]
}