{
 "title": "TSS Payments Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Payment Processing Started (Time Series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(tss_payment_processing_started{event_type=\"payment_processing_started\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Processing Started (Metrics)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "tss_payment_processing_started", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Payment Transaction Successful (Time Series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(tss_payment_transaction_successful{event_type=\"payment_processing_successful\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(tss_payment_transaction_successful{event_type=\"payment_reprocessing_successful\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Transaction Successful (Metrics)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "tss_payment_transaction_successful",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Reconciliation Successful (Time Series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count(tss_payment_reconciliation_successful{event_type=\"payment_reconciliation_successful\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Reconciliation Successful (Metrics)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "tss_payment_reconciliation_successful",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Error (Time Series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count(tss_payment_error{event_type=\"payment_marked_for_reprocessing\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(tss_payment_error{event_type=\"payment_failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Error (Metrics)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "tss_payment_error", "legendFormat": "__auto" }
   ]
  }
 ]
}