// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/stellar/stellar-disbursement-platform-backend/internal/transactionsubmission/services"
	mock "github.com/stretchr/testify/mock"
)

// MockChAccCmdServiceInterface is an autogenerated mock type for the ChAccCmdServiceInterface type
type MockChAccCmdServiceInterface struct {
	mock.Mock
}

// CreateChannelAccounts provides a mock function with given fields: ctx, chAccService, count
func (_m *MockChAccCmdServiceInterface) CreateChannelAccounts(ctx context.Context, chAccService services.ChannelAccountsService, count int) error {
	ret := _m.Called(ctx, chAccService, count)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ChannelAccountsService, int) error); ok {
		r0 = rf(ctx, chAccService, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteChannelAccount provides a mock function with given fields: ctx, chAccService, opts
func (_m *MockChAccCmdServiceInterface) DeleteChannelAccount(ctx context.Context, chAccService services.ChannelAccountsService, opts services.DeleteChannelAccountsOptions) error {
	ret := _m.Called(ctx, chAccService, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ChannelAccountsService, services.DeleteChannelAccountsOptions) error); ok {
		r0 = rf(ctx, chAccService, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnsureChannelAccountsCount provides a mock function with given fields: ctx, chAccService, count
func (_m *MockChAccCmdServiceInterface) EnsureChannelAccountsCount(ctx context.Context, chAccService services.ChannelAccountsService, count int) error {
	ret := _m.Called(ctx, chAccService, count)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ChannelAccountsService, int) error); ok {
		r0 = rf(ctx, chAccService, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListChannelAccounts provides a mock function with given fields: ctx, opts
func (_m *MockChAccCmdServiceInterface) ListChannelAccounts(ctx context.Context, opts services.ListChannelAccountsOptions) error {
	ret := _m.Called(ctx, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ListChannelAccountsOptions) error); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyChannelAccounts provides a mock function with given fields: ctx, chAccService, deleteInvalidAccounts
func (_m *MockChAccCmdServiceInterface) VerifyChannelAccounts(ctx context.Context, chAccService services.ChannelAccountsService, deleteInvalidAccounts bool) error {
	ret := _m.Called(ctx, chAccService, deleteInvalidAccounts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ChannelAccountsService, bool) error); ok {
		r0 = rf(ctx, chAccService, deleteInvalidAccounts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockChAccCmdServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockChAccCmdServiceInterface creates a new instance of MockChAccCmdServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockChAccCmdServiceInterface(t mockConstructorTestingTNewMockChAccCmdServiceInterface) *MockChAccCmdServiceInterface {
	mock := &MockChAccCmdServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
