name: Assign PR Author

on:
  pull_request:
    types: [opened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Assign PR author
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const prNumber = context.payload.pull_request.number;
            // Check if the author is dependabot
            if (prAuthor === "dependabot[bot]") {
              console.log("Skipping assignment for Dependabot PR.");
            } else {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                assignees: [prAuthor],
              });
              console.log(`Assigned PR #${prNumber} to ${prAuthor}.`);
            }
