apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sdp-secrets
  namespace: sdp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-backend
    kind: SecretStore
  target:
    name: sdp-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_DATA_USERNAME
      remoteRef:
        key: /sdp/dev/SECRET_DATA_USERNAME
    - secretKey: SECRET_DATA_PASSWORD
      remoteRef:
        key: /sdp/dev/SECRET_DATA_PASSWORD
    - secretKey: DATA_SERVER
      remoteRef:
        key: /sdp/dev/DATA_SERVER
    - secretKey: DISTRIBUTION_SEED
      remoteRef:
        key: /sdp/dev/DISTRIBUTION_SEED
    - secretKey: DISTRIBUTION_PUBLIC_KEY
      remoteRef:
        key: /sdp/dev/DISTRIBUTION_PUBLIC_KEY
    - secretKey: SEP10_SIGNING_PRIVATE_KEY
      remoteRef:
        key: /sdp/dev/SEP10_SIGNING_PRIVATE_KEY
    - secretKey: SEP10_SIGNING_PUBLIC_KEY
      remoteRef:
        key: /sdp/dev/SEP10_SIGNING_PUBLIC_KEY
    - secretKey: SECRET_SEP10_SIGNING_SEED
      remoteRef:
        key: /sdp/dev/SECRET_SEP10_SIGNING_SEED
    - secretKey: EC256_PRIVATE_KEY
      remoteRef:
        key: /sdp/dev/EC256_PRIVATE_KEY
    - secretKey: EC256_PUBLIC_KEY
      remoteRef:
        key: /sdp/dev/EC256_PUBLIC_KEY
    - secretKey: CHANNEL_ACCOUNT_ENCRYPTION_PASSPHRASE
      remoteRef:
        key: /sdp/dev/CHANNEL_ACCOUNT_ENCRYPTION_PASSPHRASE
    - secretKey: DISTRIBUTION_ACCOUNT_ENCRYPTION_PASSPHRASE
      remoteRef:
        key: /sdp/dev/DISTRIBUTION_ACCOUNT_ENCRYPTION_PASSPHRASE 
    - secretKey: SECRET_SEP10_JWT_SECRET
      remoteRef:
        key: /sdp/dev/SECRET_SEP10_JWT_SECRET
    - secretKey: SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET
      remoteRef:
        key: /sdp/dev/SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET
    - secretKey: SECRET_SEP24_MORE_INFO_URL_JWT_SECRET
      remoteRef:
        key: /sdp/dev/SECRET_SEP24_MORE_INFO_URL_JWT_SECRET
    - secretKey: DATABASE_URL
      remoteRef:
        key: /sdp/dev/DATABASE_URL
    - secretKey: SEP24_JWT_SECRET
      remoteRef:
        key: /sdp/dev/SEP24_JWT_SECRET
    - secretKey: RECAPTCHA_SITE_KEY
      remoteRef:
        key: /sdp/dev/RECAPTCHA_SITE_KEY  
    - secretKey: RECAPTCHA_SITE_SECRET_KEY
      remoteRef:
        key: /sdp/dev/RECAPTCHA_SITE_SECRET_KEY 
    - secretKey: ADMIN_API_KEY
      remoteRef:
        key: /sdp/dev/ADMIN_API_KEY
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /sdp/dev/AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /sdp/dev/AWS_SECRET_ACCESS_KEY
