apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sdp-secrets
  namespace: ${NAMESPACE}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-backend
    kind: SecretStore
  target:
    name: sdp-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name: 
          regexp: "^/${NAMESPACE}/${ENVIRONMENT}/"
      rewrite:
        - regexp:
            source: "^/${NAMESPACE}/${ENVIRONMENT}/(.*)$"
            target: "$1"