apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sdp-secrets
  namespace: sdp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-backend
    kind: SecretStore
  target:
    name: sdp-secrets
    creationPolicy: Owner
  data:
    - secretKey: DISTRIBUTION_SEED
      remoteRef:
        key: /sdp/prod/DISTRIBUTION_SEED
    - secretKey: DISTRIBUTION_PUBLIC_KEY
      remoteRef:
        key: /sdp/prod/DISTRIBUTION_PUBLIC_KEY
    - secretKey: SEP10_SIGNING_PRIVATE_KEY
      remoteRef:
        key: /sdp/prod/SEP10_SIGNING_PRIVATE_KEY
    - secretKey: SEP10_SIGNING_PUBLIC_KEY
      remoteRef:
        key: /sdp/prod/SEP10_SIGNING_PUBLIC_KEY
    - secretKey: EC256_PRIVATE_KEY
      remoteRef:
        key: /sdp/prod/EC256_PRIVATE_KEY
    - secretKey: CHANNEL_ACCOUNT_ENCRYPTION_PASSPHRASE
      remoteRef:
        key: /sdp/prod/CHANNEL_ACCOUNT_ENCRYPTION_PASSPHRASE
    - secretKey: DISTRIBUTION_ACCOUNT_ENCRYPTION_PASSPHRASE
      remoteRef:
        key: /sdp/prod/DISTRIBUTION_ACCOUNT_ENCRYPTION_PASSPHRASE 
    - secretKey: DATABASE_URL
      remoteRef:
        key: /sdp/prod/DATABASE_URL
    - secretKey: SEP24_JWT_SECRET
      remoteRef:
        key: /sdp/prod/SEP24_JWT_SECRET
    - secretKey: RECAPTCHA_SITE_SECRET_KEY
      remoteRef:
        key: /sdp/prod/RECAPTCHA_SITE_SECRET_KEY 
    - secretKey: ADMIN_API_KEY
      remoteRef:
        key: /sdp/prod/ADMIN_API_KEY
    - secretKey: ADMIN_ACCOUNT
      remoteRef:
        key: /sdp/prod/ADMIN_ACCOUNT