global:
  isPubnet: true
  ephemeralDatabase: false
  eventBroker:
    type: "NONE"

sdp:
  image:
    tag: "6.6.1"
  route:
    domain: sdp-backend.example.org
    mtnDomain: "*.sdp-backend.example.org"
  deployment:
    podAnnotations:
      prometheus.io/path: /metrics
      prometheus.io/port: '{{ include "sdp.metricsPort" . }}'
      prometheus.io/scrape: "true"
    strategy:
      # Ensure we upgrade 1 pod at a time to avoid migration races
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
  # =========================== START sdp.kubeSecrets ===========================
  kubeSecrets:
    secretName: sdp-secrets
    create: false
  # =========================== START sdp.configMap ===========================
  configMap:
    data:
      INSTANCE_NAME: "SDP-prod"
      ENVIRONMENT: "prod"
      SCHEDULER_RECEIVER_INVITATION_JOB_SECONDS: "10"
      SCHEDULER_PAYMENT_JOB_SECONDS: "10"
      SDP_UI_BASE_URL: "https://dashboard.example.org"
      RECAPTCHA_SITE_KEY: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
  # =========================== START sdp.ingress ===========================
  ingress:
    enabled: true
    className: "ingress-public"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
          - 'sdp-backend.example.org'
          - '*.sdp-backend.example.org'
        secretName: sdp-backend-cert

# ============================= tss ===================================
tss:
  deployment:
    podAnnotations:
      prometheus.io/path: /metrics
      prometheus.io/port: '{{ include "tss.metricsPort" . }}'
      prometheus.io/scrape: "true"
    strategy:
      type: "RollingUpdate"
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
  kubeSecrets:
    create: false
    secretName: sdp-secrets
  configMap:
    data:
      NUM_CHANNEL_ACCOUNTS: "3"
      MAX_BASE_FEE: "100"
      ENVIRONMENT: "prod"
# ============================= dashboard ===================================
dashboard:
  image:
    fullName: stellar/stellar-disbursement-platform-frontend:6.6.0
  enabled: true
  route:
    domain: "dashboard.example.org"
    mtnDomain: "*.dashboard.example.org"
  deployment:
    strategy:
      type: "RollingUpdate"
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
  configMap:
    data:
      RECAPTCHA_SITE_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
  ingress:
    enabled: true
    className: "ingress-public"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
          - 'dashboard.example.org'
          - '*.dashboard.example.org'
        secretName: sdp-dashboard-cert
